USE [master]
GO

/****** Object:  Database [ViewershipForecastDB]    Script Date: 14.04.2019 13:00:14 ******/
CREATE DATABASE [ViewershipForecastDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ViewershipForecastDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BARTEK\MSSQL\DATA\ViewershipForecastDB.mdf' , SIZE = 925696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ViewershipForecastDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.BARTEK\MSSQL\DATA\ViewershipForecastDB_log.ldf' , SIZE = 2105344KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ViewershipForecastDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ViewershipForecastDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ViewershipForecastDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ViewershipForecastDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ViewershipForecastDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ViewershipForecastDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ViewershipForecastDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ViewershipForecastDB] SET  MULTI_USER 
GO

ALTER DATABASE [ViewershipForecastDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ViewershipForecastDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ViewershipForecastDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ViewershipForecastDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ViewershipForecastDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ViewershipForecastDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ViewershipForecastDB] SET  READ_WRITE 
GO

