//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViewershipPrognoseModulEntities : DbContext
    {
        public ViewershipPrognoseModulEntities()
            : base("name=ViewershipPrognoseModulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Program_tv> Program_tv { get; set; }
        public virtual DbSet<Program_type> Program_type { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Weather> Weather { get; set; }
    }
}
